### ISSUE TITLE
编译bug

### ISSUE THREAD

**Issue by cavalleria** [rockcarry/ffcnn#1]
`>> bash build.sh`
``ffcnn.c: In function ‘net_load’:
ffcnn.c:216:96: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  if ((fp = fopen(fweights, "rb"))) { fseek (fp, sizeof(WEIGHTS_FILE_HEADER), SEEK_SET); fread (net->weight_buf, 1, net->weight_size * sizeof(float), fp); fclose(fp); }
                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ffcnn.c: In function ‘load_file_to_buffer’:
ffcnn.c:27:16: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     if (buf) { fread(buf, 1, size, fp); buf[size] = '\0'; }
                ^~~~~~~~~~~~~~~~~~~~~~~
/tmp/ccOQFshr.o: In function `net_forward.part.7':
ffcnn.c:(.text+0x154d): undefined reference to `exp'
ffcnn.c:(.text+0x2157): undefined reference to `exp'
ffcnn.c:(.text+0x2377): undefined reference to `exp'
ffcnn.c:(.text+0x2397): undefined reference to `exp'
ffcnn.c:(.text+0x24ad): undefined reference to `exp'
/tmp/ccOQFshr.o:ffcnn.c:(.text+0x24e1): more undefined references to `exp' follow
collect2: error: ld returned 1 exit status ``

System info: gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

修改build.sh为`gcc -Wall -O3 bmpfile.c ffcnn.c -o ffcnn -lm`可以编译通过。

**Comment by rockcarry** [comment]
patch has been merged, this issue can be close.
