### ISSUE TITLE
调整图片大小的参数？

### ISSUE THREAD

**Issue by b51ak47** [rockcarry/ffcnn#3]
调整图片test.bmp大小的参数在哪里？ 是不是你训练的时候是固定的，所以不能改，只能输入640 424的大小？
谢谢

**Comment by rockcarry** [comment]
你换一个其他大小的图片测试下，应该是没有问题的。

**Comment by b51ak47** [comment]
您好
我有测试过，您都是固定大小的图才可以
我才会想说问您看看的~

**Comment by rockcarry** [comment]
我试过任意一张 bmp 图片，都是可以检测的。要注意的是必须是 24bit 的 bmp 图片。
我这边都是正常的，你测试有问题的话，提供下有问题的图片给我。

**Comment by b51ak47** [comment]
HI ~

我随便拉一张bmp 去测试的，相机拍出来是640 480 ~
可是真的无法读取，看您代码也好像没有特别固定大小~
或是您github的代码有更新过?
还是您可以试试我的图呢?
链接：https://pan.baidu.com/s/1en_3gANVhtPS1zJgSPT6Pw 
提取码：qby0


![擷取1008](https://user-images.githubusercontent.com/40915044/136494831-40934b9a-e51a-4e7a-ac97-7131bee793c0.PNG)

**Comment by b51ak47** [comment]
大神的程式没有问题 我发现那张bmp header 好像有问题~
感谢大神
![image](https://user-images.githubusercontent.com/40915044/136524846-42dfbd61-a716-4dc6-bdfc-5e414ccbbc61.png)
